- name: Ensure that data folders has right permissions
  file:
    path: '{{ item }}'
    group: postgres
    mode: 0710
  loop:
    - /var/data/
    - /var/data/base
    - /var/data/base/global
  when: inventory_hostname in groups['db']

- name: Ensure that file pg_control has read group permissions
  file:
    path: /var/data/base/global/pg_control
    mode: 0640    
  when: inventory_hostname in groups['db']

- name: Ensure that user {{ backup_user }} have read access to db files
  command: setfacl -Rm u:dbbackup:rwX /var/data/
  when: inventory_hostname in groups['db']
  tags:
    - acl
#   acl:
#     path: /var/data/base/
#     entity: postgres
#     etype: group
#     permissions: r
#     recursive: yes
#     default: no
#     state: present
#   when: inventory_hostname in groups['db']
#   tags:
#     - acl

- name: Ensure that backup dir is exists
  file:
    path: "{{ backup_folder }}"
    state: directory
    owner: "{{ backup_user }}"
    group: postgres
    mode: 0700
  tags:
    - backup_dir
  when: inventory_hostname in groups['backup']

- name: Initiate backup folder on backup host
  command: creates="{{ backup_folder }}/wal" pg_probackup-11 init -B {{ backup_folder }}
  become_user: "{{ backup_user }}"
  when: inventory_hostname in groups['backup']

- name: Add scope to backup
  command: creates="{{backup_folder}}/backups/{{backup_scope}}" pg_probackup-11 add-instance -B {{ backup_folder }} -D /var/data/base --instance db-mt --remote-host=13.48.80.25
  become_user: "{{ backup_user }}"
  when: inventory_hostname in groups['backup']
  tags:
    - add-instance
  
